name: asgard

packages:
  - asgard/**
  - asgard_core/**
  - test_utils/**

scripts:
  analyze:
    run: |
      melos exec -c 5 -- \
        dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.
  test:asgard:
    run: |
      melos exec -c 1 --fail-fast -- \
        "flutter test --no-pub"
    description: |
      Run `flutter test` for 'asgard' package.
    select-package:
      scope: "asgard"
  test:asgard_core:
    run: |
      melos exec -c 1 --fail-fast -- \
        "flutter test --no-pub"
    description: |
      Run `flutter test` for 'asgard_core' package.
    select-package:
